import "server-only";
import type { TemplateDefinition, TemplateKey, TemplateVars } from "./types";

/**
 * Code defaults for every message (docs/architecture.md §9.2). A `MessageTemplate` row with the
 * same key overrides one; deleting the row („Reveniți la textul implicit”) restores it.
 *
 * Formal register, no exclamation marks, comma-below ș ț. Patient messages never contain the
 * reason for the visit or any health information; `{{motiv}}` exists only in clinic templates.
 */
export const DEFAULT_TEMPLATES: Record<TemplateKey, TemplateDefinition> = {
  "booking.received.email": {
    key: "booking.received.email",
    channel: "EMAIL",
    kind: "CONFIRMARE_PROGRAMARE",
    name: "Cerere de programare primită (e-mail)",
    audience: "pacient",
    description: "Trimis automat după o programare online. Recepția sună ca să confirme.",
    subject: "Am primit cererea de programare: {{data}}, ora {{ora}}",
    body: [
      "Bună ziua, {{prenume}},",
      "",
      "Am primit cererea dumneavoastră de programare la {{clinica}}, {{data}}, ora {{ora}}.",
      "",
      "Colegii de la recepție vă sună de la {{telefonClinica}} ca să confirme ora. Programarea este sigură după această confirmare.",
      "",
      "Adresa: {{adresa}}",
      "",
      "Puteți confirma sau anula programarea aici: {{link}}",
      "",
      "Echipa Dental Arena",
    ].join("\n"),
  },
  "booking.confirmed.sms": {
    key: "booking.confirmed.sms",
    channel: "SMS",
    kind: "CONFIRMARE_PROGRAMARE",
    name: "Programare confirmată (SMS)",
    audience: "pacient",
    description: "Trimis când recepția confirmă programarea, doar pacienților care au acceptat SMS-uri.",
    subject: null,
    body: "Programarea de {{data}}, ora {{ora}}, la Dental Arena {{clinicaScurt}} este confirmată. Dacă nu mai puteți veni, sunați la {{telefonClinica}}.",
  },
  "booking.confirmed.email": {
    key: "booking.confirmed.email",
    channel: "EMAIL",
    kind: "CONFIRMARE_PROGRAMARE",
    name: "Programare confirmată (e-mail)",
    audience: "pacient",
    description: "Trimis când recepția confirmă programarea.",
    subject: "Programarea de {{data}}, ora {{ora}}, este confirmată",
    body: [
      "Bună ziua, {{prenume}},",
      "",
      "Programarea dumneavoastră de {{data}}, ora {{ora}}, la {{clinica}} este confirmată.",
      "",
      "Adresa: {{adresa}}",
      "",
      "Dacă nu mai puteți veni, anulați programarea aici: {{link}} sau sunați la {{telefonClinica}}.",
      "",
      "Echipa Dental Arena",
    ].join("\n"),
  },
  "reminder.sms": {
    key: "reminder.sms",
    channel: "SMS",
    kind: "REMINDER",
    name: "Reamintire cu 24 de ore înainte (SMS)",
    audience: "pacient",
    description: "Trimis automat cu o zi înainte, doar pacienților care au acceptat SMS-uri.",
    subject: null,
    body: "Dental Arena: vă reamintim programarea de {{data}}, ora {{ora}}, la {{clinica}}. Confirmați sau anulați: {{link}}",
  },
  "reminder.email": {
    key: "reminder.email",
    channel: "EMAIL",
    kind: "REMINDER",
    name: "Reamintire cu 24 de ore înainte (e-mail)",
    audience: "pacient",
    description: "Trimis automat cu o zi înainte, când pacientul are o adresă de e-mail.",
    subject: "Vă reamintim programarea de {{data}}, ora {{ora}}",
    body: [
      "Bună ziua, {{prenume}},",
      "",
      "Vă reamintim programarea de {{data}}, ora {{ora}}, la {{clinica}}, cu {{medic}}.",
      "",
      "Adresa: {{adresa}}",
      "",
      "Ce să aveți la dumneavoastră: buletinul și lista medicamentelor pe care le luați.",
      "",
      "Confirmați sau anulați programarea aici: {{link}}",
      "Pentru alte modificări sunați la {{telefonClinica}}.",
      "",
      "Echipa Dental Arena",
    ].join("\n"),
  },
  "cancel.sms": {
    key: "cancel.sms",
    channel: "SMS",
    kind: "ANULARE",
    name: "Programare anulată de clinică (SMS)",
    audience: "pacient",
    description: "Trimis când clinica anulează programarea.",
    subject: null,
    body: "Dental Arena: programarea de {{data}}, ora {{ora}}, la {{clinicaScurt}} a fost anulată. Pentru o nouă programare sunați la {{telefonClinica}}.",
  },
  "cancel.email": {
    key: "cancel.email",
    channel: "EMAIL",
    kind: "ANULARE",
    name: "Programare anulată de clinică (e-mail)",
    audience: "pacient",
    description: "Trimis când clinica anulează programarea.",
    subject: "Programarea de {{data}}, ora {{ora}}, a fost anulată",
    body: [
      "Bună ziua, {{prenume}},",
      "",
      "Programarea dumneavoastră de {{data}}, ora {{ora}}, la {{clinica}} a fost anulată.",
      "",
      "Pentru o nouă programare sunați la {{telefonClinica}}. Vă găsim cu plăcere o altă oră.",
      "",
      "Echipa Dental Arena",
    ].join("\n"),
  },
  "moved.sms": {
    key: "moved.sms",
    channel: "SMS",
    kind: "MODIFICARE",
    name: "Programare mutată (SMS)",
    audience: "pacient",
    description: "Trimis când programarea primește o dată sau o oră nouă.",
    subject: null,
    body: "Dental Arena: programarea dumneavoastră a fost mutată pe {{data}}, ora {{ora}}, la {{clinica}}. Confirmați sau anulați: {{link}}",
  },
  "moved.email": {
    key: "moved.email",
    channel: "EMAIL",
    kind: "MODIFICARE",
    name: "Programare mutată (e-mail)",
    audience: "pacient",
    description: "Trimis când programarea primește o dată sau o oră nouă.",
    subject: "Programarea a fost mutată: {{data}}, ora {{ora}}",
    body: [
      "Bună ziua, {{prenume}},",
      "",
      "Programarea dumneavoastră a fost mutată pe {{data}}, ora {{ora}}, la {{clinica}}, cu {{medic}}.",
      "",
      "Adresa: {{adresa}}",
      "",
      "Confirmați sau anulați noua oră aici: {{link}}",
      "Pentru alte modificări sunați la {{telefonClinica}}.",
      "",
      "Echipa Dental Arena",
    ].join("\n"),
  },
  "clinic.newLead.email": {
    key: "clinic.newLead.email",
    channel: "EMAIL",
    kind: "NOTIFICARE_CLINICA",
    name: "Cerere nouă din site (pentru clinică)",
    audience: "clinica",
    description: "Trimis recepției la fiecare cerere nouă. Detaliile medicale rămân doar în Cabinet.",
    subject: "Cerere nouă din site: {{nume}}, {{motiv}}",
    body: [
      "A sosit o cerere nouă din site.",
      "",
      "Nume: {{nume}}",
      "Tip: {{motiv}}",
      "Clinica: {{clinica}}",
      "",
      "Deschideți cererea în Cabinet: {{link}}",
    ].join("\n"),
  },
  "clinic.cancelled.email": {
    key: "clinic.cancelled.email",
    channel: "EMAIL",
    kind: "NOTIFICARE_CLINICA",
    name: "Programare anulată de pacient (pentru clinică)",
    audience: "clinica",
    description: "Trimis recepției când un pacient anulează prin linkul din SMS sau e-mail.",
    subject: "Programare anulată de pacient: {{data}}, ora {{ora}}",
    body: [
      "{{nume}} a anulat prin link programarea de {{data}}, ora {{ora}}, la {{clinica}}, cu {{medic}}.",
      "",
      "Ora este din nou liberă. Detalii în Cabinet: {{link}}",
    ].join("\n"),
  },
};

/** Sample values for the editor preview (fictitious patient, real clinic). */
export const SAMPLE_VARIABLES: Required<TemplateVars> = {
  prenume: "Maria",
  nume: "Maria Suciu",
  data: "marți, 7 octombrie",
  ora: "10:30",
  clinica: "Dental Arena Cristești",
  clinicaScurt: "Cristești",
  adresa: "str. Principală 536J/1, Cristești, jud. Mureș",
  telefonClinica: "0265 326 316",
  medic: "Dr. Andrei Marcoci",
  // Real length (§6.6), so the SMS preview counts segments as the clinic will be billed.
  link: "https://dentalarena.ro/p/Y21nOHgyazR2MDAwYjA4bDdkM2Y5cTF6cg.0.tmkvi0.fobZDs_MJ6WltrPPWX8ppd",
  motiv: "Programare online",
};
